### ISSUE TITLE
feat: pvc mounting script and template

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-nerds#77]
Idea and template courtesy of @craigyu.

```yml
apiVersion: v1
kind: Pod
metadata:
    name: pvc-inspect-pod
    namespace: a4b31c-test
spec:
    containers:
        - name: pvc-inspector
          image: busybox
          command: ["sleep", "3600"]
          volumeMounts:
              - mountPath: "/mnt/pvc"
                name: db-backup-pvc
    volumes:
        - name: db-backup-pvc
          persistentVolumeClaim:
              claimName: fom-test-database-backup
    restartPolicy: Never

```
